apiVersion: v1
kind: Pod
metadata:
  name: pod-processing-large-reports
  labels:
    app: pod
spec:
  containers:
  - name: processing-large-reports-in-browser
    image: gulhermepsantos/processing-large-reports-in-browser:latest
    ports: 
    - containerPort: 3000
