apiVersion: v1
kind: Pod
metadata:
  name: processing-large-reports-in-browser-pod
spec:
  containers:
  - name: processing-large-reports-in-browser
    image: gulhermepsantos/processing-large-reports-in-browser:latest
    ports: 
    - containerPort: 3000
