apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-app
spec:
  replicas: 4
  selector:
    matchLabels:
        app.kubernetes.io/name: processing-large-reports-in-browser
        app.kubernetes.io/part-of: node.js
  template:
    metadata:
      labels:
        app.kubernetes.io/name: processing-large-reports-in-browser
        app.kubernetes.io/part-of: node.js
    spec:
      containers:
        - name: processing-large-reports-in-browser
          image: gulhermepsantos/processing-large-reports-in-browser:latest
          resources:
            requests:
              memory: 100Mi
              cpu: "100m"
            limits:
              memory: 250Mi
              cpu: "250m"
          ports: 
          - containerPort: 3000        
          