apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    app: processing-large-reports-in-browser  
spec:
  replicas: 3
  selector: 
    matchLabels:
      app.kubernetes.io/name: processing-large-reports-in-browser
      app.kubernetes.io/part-of: node.js
  template: 
    metadata:
      labels: 
        app.kubernetes.io/name: processing-large-reports-in-browser
        app.kubernetes.io/part-of: node.js
    spec: 
      containers:
        - name: processing-large-reports-in-browser
          image: gulhermepsantos/processing-large-reports-in-browser:latest
          ports: 
          - containerPort: 3000